spring:
    application.name: pg-index-health-spring-boot-demo
    main.banner-mode: off
    liquibase:
        change-log: classpath:/db/changelog/db.changelog-master.yaml

logging:
    level:
        root: INFO
        org.springframework: INFO

server:
    port: 8080
    servlet:
        context-path: /api

management:
    server:
        port: 8081
    endpoints:
        enabled-by-default: false
        web.exposure.include: health,prometheus,liquibase,info,threaddump,heapdump
    endpoint:
        health:
            enabled: true
            probes.enabled: true
            group:
                readiness:
                    include: readinessState,db
        prometheus:
            enabled: true
        liquibase:
            enabled: true
        info:
            enabled: true
        threaddump:
            enabled: true
        heapdump:
            enabled: true
    metrics:
        distribution:
            percentiles-histogram:
                "[http.server.requests]": true
        export:
            prometheus.enabled: true
    health:
        livenessstate:
            enabled: true
        readinessstate:
            enabled: true
